### PR TITLE
Avoid crashing if there is a user in the export who doesn't have a Verif...

### PR DESCRIPTION
**Pull request by alexdavies74**
...iedEmail

### CODE REVIEW

**Comment by alexdavies74** [comment]
The travis ci tests failed because they only work at certain times of day if you're not in UTC?

**Comment by theospears** [comment]
Mixed tabs and spaces in a file is the worst thing in the world. Shall we just mass-convert this project to spaces?

**Comment by alexdavies74** [comment]
Sure

**Comment by alexdavies74** [comment]
Are you asking me to do that before merging this pull request. Seems unrelated.

**Comment by theospears** [comment]
I just noticed it in this diff - the file is tabbed and the diff introduces random spaces so the indentation looks wrong. Don't think that needs to hold up merging this though.

**Comment by theospears** [comment]
PR otherwise looks fine.

**Pull request merged**
